[build]
# Optimize compilation
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+crt-static"
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static"
]

